#!/bin/bash

#############################
## May need chmod +x file
##
## RUN script from R Console
# system("/home/ELXSJ/geyser_rsconnect/sync.sh")
#
# Run from shell
# bash <filename>
#
# Linux environment Prerequisites
# sudo apt-get install --reinstall ca-certificates
#
# git config --global user.email "my_email.com"
# git config --global user.name "memadsen"
#
## Optional: Reset Gitignore after making changes
## git rm -r --cached .
##
## Run this script in default branch
## git branch -d <my_feature_branch> ## never do this to main branch!!
#############################

## Paramaters
dt=$(date '+%d/%m/%Y %H:%M:%S')

BRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

## script
# echo -e "Hi Hi Hi $(whoami) ----------------------- "
# echo " "

# Check if remote has changed and need to pull
changed=0
git remote update && git status -uno | grep -q 'Your branch is behind' && changed=1
if [ $changed = 1 ]; then
    git pull
    echo " "
    echo "-------Updated Remote successfully-------";
else
    echo " "
    echo "-------Remote is Up-to-date-------"
fi


echo "current git branch == $BRANCH"
echo ""
read -p "Do you wish to commit changes to repo (yes/no) " yn
echo ""

case $yn in
	yes ) echo ok, we will proceed;;
	no ) echo exiting...;
		exit;;
	* ) echo invalid response;
		exit 1;;
esac

git add .

git commit -m "$dt ¯\_(ツ)_/¯"

git push #-u origin "$BRANCH"